export interface RecipeData {
  id: string;
  title: string;
  description?: string;
  ingredients: string[];
  steps: string[];
  time: string;
  servings: string;
  region: string;
  image?: string;
  videoUrl?: string;
  createdAt: string;
  userId?: string;
}

export interface WebSocketMessage {
  type: "transcript" | "partial_recipe" | "final_recipe" | "tts_audio" | "error" | "status";
  data: any;
}

export const API_BASE_URL = "http://localhost:8000";
export const WS_AUDIO_URL = "ws://localhost:8000/ws/audio";

export const REGIONS = ["Kerala", "Punjab", "Tamil Nadu", "Gujarat", "Maharashtra", "Karnataka", "Hyderabad", "Rajasthan", "Bengal", "Goa"];

export const DEMO_RECIPES: RecipeData[] = [
  // ─── KERALA (5) ───
  { id: "k1", title: "Kerala Fish Curry", description: "Tangy and spicy fish curry with raw mango and coconut milk.", ingredients: ["500g fish (kingfish/seer)", "1 raw mango, sliced", "1 cup coconut milk", "2 tbsp coconut oil", "1 tsp turmeric", "2 tsp red chili powder", "Curry leaves", "1 tsp fenugreek seeds", "Salt to taste"], steps: ["Clean and marinate fish with turmeric and salt.", "Heat coconut oil, add fenugreek seeds and curry leaves.", "Add sliced onions, ginger, and green chilies. Sauté well.", "Add chili powder, turmeric, and raw mango. Cook 5 min.", "Pour coconut milk, bring to simmer, add fish pieces.", "Cook on low 10 min. Let rest before serving."], time: "30 min", servings: "4", region: "Kerala", image: "https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80", createdAt: "2026-03-01T10:00:00Z" },
  { id: "k2", title: "Appam with Stew", description: "Lacy rice hoppers served with creamy vegetable stew.", ingredients: ["2 cups rice", "1/2 cup coconut", "1 tsp yeast", "1 tsp sugar", "Mixed vegetables", "1 cup coconut milk", "Whole spices", "Curry leaves"], steps: ["Soak rice 4 hours, grind with coconut to smooth batter.", "Add yeast and sugar, ferment overnight.", "Pour ladle of batter into appam pan, swirl to create lacy edges.", "For stew: cook vegetables with coconut milk and whole spices.", "Serve appam hot with creamy stew."], time: "40 min", servings: "4", region: "Kerala", image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80", createdAt: "2026-03-01T11:00:00Z" },
  { id: "k3", title: "Puttu & Kadala Curry", description: "Steamed rice cake cylinders with spiced black chickpea curry.", ingredients: ["2 cups rice flour", "1 cup grated coconut", "1 cup black chickpeas (soaked overnight)", "2 onions", "2 tomatoes", "2 tsp chili powder", "1 tsp coriander powder", "Coconut oil"], steps: ["Steam rice flour with layers of grated coconut in puttu maker.", "Pressure cook soaked chickpeas until soft.", "Sauté onions, add tomatoes, spices, and cooked chickpeas.", "Simmer until thick gravy forms.", "Serve puttu with kadala curry."], time: "45 min", servings: "4", region: "Kerala", image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80", createdAt: "2026-03-01T12:00:00Z" },
  { id: "k4", title: "Avial", description: "Mixed vegetables in coconut-yogurt sauce, a Kerala Onam Sadhya staple.", ingredients: ["Mixed vegetables (drumstick, yam, beans, carrot)", "1 cup grated coconut", "1/2 cup yogurt", "2 green chilies", "Curry leaves", "Coconut oil", "Turmeric"], steps: ["Cut vegetables into long strips.", "Cook with turmeric and salt until tender.", "Grind coconut and green chilies to coarse paste.", "Add coconut paste to vegetables, mix gently.", "Stir in yogurt, add curry leaves and coconut oil.", "Do not boil after adding yogurt."], time: "35 min", servings: "4", region: "Kerala", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80", createdAt: "2026-03-01T13:00:00Z" },
  { id: "k5", title: "Payasam", description: "Rich Kerala dessert made with vermicelli, milk, and jaggery.", ingredients: ["1 cup vermicelli", "3 cups milk", "1/2 cup jaggery", "2 tbsp ghee", "Cashews", "Raisins", "Cardamom"], steps: ["Roast vermicelli in ghee until golden.", "Boil milk, add roasted vermicelli.", "Dissolve jaggery in warm water, strain and add.", "Simmer until thick and creamy.", "Fry cashews and raisins in ghee, garnish.", "Serve warm or chilled."], time: "25 min", servings: "6", region: "Kerala", image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80", createdAt: "2026-03-01T14:00:00Z" },

  // ─── PUNJAB (5) ───
  { id: "p1", title: "Butter Chicken", description: "Creamy tomato-based curry with tender tandoori chicken.", ingredients: ["500g chicken", "1 cup tomato puree", "1/2 cup cream", "2 tbsp butter", "1 tbsp ginger-garlic paste", "1 tsp garam masala", "1 tsp kashmiri chili", "Kasuri methi", "Salt to taste"], steps: ["Marinate chicken with yogurt and spices. Grill or pan-fry.", "Sauté ginger-garlic paste in butter.", "Add tomato puree, cook until oil separates.", "Add spices, cream, and grilled chicken.", "Simmer 10 min. Garnish with kasuri methi and cream."], time: "45 min", servings: "4", region: "Punjab", image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80", createdAt: "2026-03-02T10:00:00Z" },
  { id: "p2", title: "Punjabi Samosa", description: "Golden fried pastry stuffed with spiced potato filling.", ingredients: ["2 cups flour", "3 potatoes, mashed", "1/2 cup peas", "1 tsp cumin", "1 tsp garam masala", "Green chilies", "Oil for frying"], steps: ["Make dough with flour, salt, oil and water. Rest 30 min.", "Prepare filling with potatoes, peas, cumin, garam masala.", "Roll dough, form cones, fill with potato mixture.", "Deep fry on medium heat until golden and crispy.", "Serve with green chutney and tamarind chutney."], time: "40 min", servings: "12 pieces", region: "Punjab", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80", createdAt: "2026-03-02T11:00:00Z" },
  { id: "p3", title: "Dal Makhani", description: "Rich and creamy black lentil curry slow-cooked to perfection.", ingredients: ["1 cup whole black urad dal", "1/4 cup rajma", "2 tbsp butter", "1 cup tomato puree", "1/2 cup cream", "1 tbsp ginger-garlic paste", "Kasuri methi"], steps: ["Soak dal and rajma overnight. Pressure cook until soft.", "Heat butter, add cumin seeds and ginger-garlic paste.", "Add tomato puree and cook until thick.", "Add cooked dal, cream, and spices.", "Simmer on low 30 min. Garnish with cream."], time: "60 min", servings: "4", region: "Punjab", image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80", createdAt: "2026-03-02T12:00:00Z" },
  { id: "p4", title: "Chole Bhature", description: "Spiced chickpea curry served with fluffy deep-fried bread.", ingredients: ["2 cups chickpeas (soaked)", "2 cups flour", "1/2 cup yogurt", "2 onions", "3 tomatoes", "Chole masala", "Amchur powder", "Oil for frying"], steps: ["Pressure cook chickpeas until soft.", "Sauté onions, add tomatoes, chole masala, amchur.", "Add chickpeas, simmer until thick.", "Make bhature dough with flour, yogurt, salt. Rest 2 hours.", "Roll and deep fry until puffed and golden.", "Serve hot with onion rings and pickle."], time: "50 min", servings: "4", region: "Punjab", image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&q=80", createdAt: "2026-03-02T13:00:00Z" },
  { id: "p5", title: "Tandoori Chicken", description: "Marinated chicken cooked in traditional clay oven style.", ingredients: ["1 whole chicken", "1 cup yogurt", "2 tbsp tandoori masala", "1 tbsp ginger-garlic paste", "Lemon juice", "Oil", "Salt"], steps: ["Make deep cuts in chicken pieces.", "Mix yogurt with all spices and marinate 4 hours.", "Preheat oven to 220°C.", "Cook 25-30 min, basting with oil.", "Serve with onion rings and mint chutney."], time: "35 min", servings: "4", region: "Punjab", image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&q=80", createdAt: "2026-03-02T14:00:00Z" },

  // ─── TAMIL NADU (5) ───
  { id: "t1", title: "Chettinad Chicken", description: "Fiery chicken curry with freshly ground spices from Chettinad region.", ingredients: ["500g chicken", "2 onions", "3 tomatoes", "1 tbsp black pepper", "1 tsp fennel seeds", "Star anise", "Kalpasi", "Curry leaves", "Coconut oil"], steps: ["Dry roast all whole spices and grind to fine powder.", "Sauté onions in coconut oil until golden.", "Add tomatoes, cook until mushy.", "Add ground spice paste and chicken pieces.", "Cook on medium heat 20 min until chicken is tender.", "Garnish with curry leaves."], time: "40 min", servings: "4", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80", createdAt: "2026-03-03T10:00:00Z" },
  { id: "t2", title: "Sambar", description: "Classic South Indian lentil stew with vegetables and tamarind.", ingredients: ["1 cup toor dal", "Mixed vegetables", "2 tbsp sambar powder", "Tamarind pulp", "Mustard seeds", "Curry leaves", "Asafoetida", "Oil"], steps: ["Cook toor dal until soft.", "Cook vegetables separately until tender.", "Extract tamarind juice, add sambar powder.", "Combine dal, vegetables, and tamarind mixture.", "Temper with mustard seeds, curry leaves, asafoetida.", "Simmer 10 min and serve with rice or idli."], time: "35 min", servings: "4", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80", createdAt: "2026-03-03T11:00:00Z" },
  { id: "t3", title: "Idli with Chutney", description: "Steamed rice cakes served with coconut chutney and sambar.", ingredients: ["2 cups rice", "1 cup urad dal", "1 cup coconut", "2 green chilies", "1 inch ginger", "Curry leaves", "Mustard seeds"], steps: ["Soak rice and dal separately for 6 hours.", "Grind to smooth batter, ferment overnight.", "Pour into idli molds, steam 12-15 min.", "Grind coconut, green chilies, ginger for chutney.", "Temper chutney with mustard seeds and curry leaves.", "Serve idli with chutney and sambar."], time: "25 min", servings: "4", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80", createdAt: "2026-03-03T12:00:00Z" },
  { id: "t4", title: "Pongal", description: "Comforting rice and lentil dish seasoned with pepper and cumin.", ingredients: ["1 cup rice", "1/2 cup moong dal", "1 tsp black pepper", "1 tsp cumin", "Curry leaves", "Cashews", "Ghee", "Ginger"], steps: ["Dry roast moong dal until golden.", "Cook rice and dal together until soft and mushy.", "Heat ghee, add pepper, cumin, curry leaves, cashews.", "Pour tempering over the cooked pongal.", "Mix well, adjust salt.", "Serve hot with sambar and chutney."], time: "30 min", servings: "4", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80", createdAt: "2026-03-03T13:00:00Z" },
  { id: "t5", title: "Rasam", description: "Tangy and peppery South Indian soup with tamarind and tomatoes.", ingredients: ["2 tomatoes", "Tamarind pulp", "1 tsp rasam powder", "1 tsp black pepper", "Curry leaves", "Mustard seeds", "Coriander leaves", "Garlic"], steps: ["Extract tamarind juice.", "Boil tomatoes, mash and strain.", "Combine tamarind water, tomato juice, rasam powder.", "Bring to a boil, add crushed garlic and pepper.", "Temper with mustard seeds and curry leaves.", "Serve hot with steamed rice."], time: "20 min", servings: "4", region: "Tamil Nadu", image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&q=80", createdAt: "2026-03-03T14:00:00Z" },

  // ─── GUJARAT (5) ───
  { id: "g1", title: "Dhokla", description: "Soft and spongy steamed gram flour cake with tangy tempering.", ingredients: ["1 cup besan (gram flour)", "1/2 cup yogurt", "1 tsp ENO fruit salt", "1 tsp sugar", "Mustard seeds", "Green chilies", "Curry leaves", "Coriander"], steps: ["Mix besan, yogurt, water, turmeric, salt, sugar.", "Add ENO, mix gently, pour into greased plate.", "Steam for 15-20 minutes.", "Temper mustard seeds, green chilies, curry leaves in oil.", "Pour tempering over dhokla.", "Garnish with coriander and serve with green chutney."], time: "25 min", servings: "4", region: "Gujarat", image: "https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&q=80", createdAt: "2026-03-04T10:00:00Z" },
  { id: "g2", title: "Undhiyu", description: "Mixed vegetable casserole, Gujarat's signature winter dish.", ingredients: ["Purple yam", "Surti papdi", "Small brinjals", "Sweet potato", "Fresh fenugreek", "Coconut", "Peanuts", "Green garlic"], steps: ["Prepare muthiya (fenugreek dumplings) and fry.", "Stuff brinjals with spice paste.", "Layer all vegetables in a pot with spices.", "Add muthiya, coconut-peanut paste.", "Cook on low heat 40 min or bake covered.", "Serve with puri and buttermilk."], time: "60 min", servings: "6", region: "Gujarat", image: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=600&q=80", createdAt: "2026-03-04T11:00:00Z" },
  { id: "g3", title: "Thepla", description: "Spiced flatbread with fenugreek leaves, perfect for travel.", ingredients: ["2 cups wheat flour", "1 cup fresh fenugreek leaves", "1/2 cup yogurt", "1 tsp turmeric", "1 tsp chili powder", "1 tsp cumin", "Oil", "Salt"], steps: ["Chop fenugreek leaves finely.", "Mix all ingredients to make soft dough.", "Rest for 15 minutes.", "Roll into thin circles.", "Cook on tawa with oil until golden spots appear.", "Serve with pickle and yogurt."], time: "30 min", servings: "8 pieces", region: "Gujarat", image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80", createdAt: "2026-03-04T12:00:00Z" },
  { id: "g4", title: "Khandvi", description: "Delicate gram flour rolls with coconut-sesame tempering.", ingredients: ["1 cup besan", "2 cups buttermilk", "1 tsp turmeric", "1 tsp ginger-green chili paste", "Mustard seeds", "Sesame seeds", "Coconut", "Curry leaves"], steps: ["Cook besan with buttermilk, turmeric, ginger paste until thick.", "Spread thin layer on greased surface.", "Let it cool slightly, then roll tightly.", "Cut into 2-inch pieces.", "Temper with mustard, sesame, coconut, curry leaves.", "Pour tempering over rolls and serve."], time: "35 min", servings: "4", region: "Gujarat", image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80", createdAt: "2026-03-04T13:00:00Z" },
  { id: "g5", title: "Gujarati Dal", description: "Sweet, sour, and spicy lentil curry unique to Gujarat.", ingredients: ["1 cup toor dal", "2 tomatoes", "1 tbsp jaggery", "1 tbsp lemon juice", "Peanuts", "Mustard seeds", "Curry leaves", "Cinnamon", "Cloves"], steps: ["Pressure cook toor dal until soft.", "Add tomato puree, jaggery, lemon juice, and spices.", "Simmer 15 min for flavors to blend.", "Temper with mustard seeds, curry leaves, peanuts.", "Add whole spices for aroma.", "Serve hot with steamed rice."], time: "30 min", servings: "4", region: "Gujarat", image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80", createdAt: "2026-03-04T14:00:00Z" },

  // ─── MAHARASHTRA (5) ───
  { id: "m1", title: "Vada Pav", description: "Mumbai's iconic spicy potato fritter sandwich.", ingredients: ["4 potatoes, boiled", "6 pav buns", "Besan for batter", "1 tsp mustard seeds", "Green chilies", "Garlic chutney", "Dry garlic chutney", "Oil for frying"], steps: ["Mash potatoes, temper with mustard seeds, curry leaves, green chilies.", "Form into round patties.", "Dip in besan batter and deep fry until golden.", "Slit pav buns, apply garlic chutney.", "Place vada inside, add dry chutney and green chili.", "Serve hot immediately."], time: "30 min", servings: "6", region: "Maharashtra", image: "https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&q=80", createdAt: "2026-03-05T10:00:00Z" },
  { id: "m2", title: "Puran Poli", description: "Sweet stuffed flatbread with chana dal and jaggery filling.", ingredients: ["2 cups wheat flour", "1 cup chana dal", "1 cup jaggery", "1/2 tsp cardamom powder", "Nutmeg", "Ghee", "Salt"], steps: ["Cook chana dal until very soft, drain.", "Mash with jaggery, cardamom, nutmeg to smooth paste.", "Make soft dough with wheat flour.", "Stuff dough balls with puran filling.", "Roll gently and cook on tawa with ghee.", "Serve warm with ghee."], time: "50 min", servings: "8", region: "Maharashtra", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80", createdAt: "2026-03-05T11:00:00Z" },
  { id: "m3", title: "Misal Pav", description: "Spicy sprouted moth bean curry topped with farsan and served with pav.", ingredients: ["1 cup moth beans, sprouted", "2 onions", "2 tomatoes", "Misal masala", "Farsan (sev mixture)", "Lemon", "Coriander", "Pav buns"], steps: ["Cook sprouted moth beans with turmeric and salt.", "Prepare spicy gravy with onions, tomatoes, and misal masala.", "Combine beans with gravy.", "Top with farsan, chopped onion, coriander, lemon.", "Serve with buttered pav."], time: "35 min", servings: "4", region: "Maharashtra", image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&q=80", createdAt: "2026-03-05T12:00:00Z" },
  { id: "m4", title: "Pav Bhaji", description: "Mashed vegetable curry served with buttered toasted buns.", ingredients: ["4 potatoes", "1 cup cauliflower", "1 cup peas", "2 capsicums", "4 tomatoes", "Pav bhaji masala", "Butter", "Pav buns"], steps: ["Boil all vegetables and mash roughly.", "Sauté onions, tomatoes, capsicum in butter.", "Add pav bhaji masala and mashed vegetables.", "Mash everything together on low heat, add butter.", "Toast pav buns with butter.", "Serve bhaji with toasted pav, onions, and lemon."], time: "40 min", servings: "4", region: "Maharashtra", image: "https://images.unsplash.com/photo-1606491956689-2ea866880049?w=600&q=80", createdAt: "2026-03-05T13:00:00Z" },
  { id: "m5", title: "Sabudana Khichdi", description: "Fasting dish made with tapioca pearls, peanuts, and potatoes.", ingredients: ["1 cup sabudana (soaked)", "2 potatoes, cubed", "1/2 cup roasted peanuts", "2 green chilies", "Cumin seeds", "Curry leaves", "Lemon juice", "Ghee"], steps: ["Soak sabudana for 4-5 hours, drain well.", "Fry potatoes in ghee until golden.", "Add cumin, green chilies, curry leaves.", "Add soaked sabudana, crushed peanuts.", "Cook on low heat until translucent.", "Add lemon juice and coriander. Serve hot."], time: "25 min", servings: "3", region: "Maharashtra", image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80", createdAt: "2026-03-05T14:00:00Z" },

  // ─── KARNATAKA (5) ───
  { id: "ka1", title: "Masala Dosa", description: "Crispy South Indian crepe filled with spiced potato filling.", ingredients: ["2 cups rice", "1 cup urad dal", "4 potatoes", "2 onions", "Mustard seeds", "Curry leaves", "Turmeric", "Oil"], steps: ["Soak rice and urad dal 6 hours, grind to batter, ferment overnight.", "Sauté mustard seeds, curry leaves, onions.", "Add mashed potatoes and turmeric.", "Spread thin batter on hot tawa.", "Place potato filling and fold.", "Serve with coconut chutney and sambar."], time: "30 min", servings: "4", region: "Karnataka", image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&q=80", createdAt: "2026-03-06T10:00:00Z" },
  { id: "ka2", title: "Bisi Bele Bath", description: "Karnataka's signature spicy lentil-rice dish with vegetables.", ingredients: ["1 cup rice", "1/2 cup toor dal", "Mixed vegetables", "2 tbsp bisi bele bath powder", "Tamarind", "Jaggery", "Ghee", "Cashews"], steps: ["Cook rice and dal together until soft.", "Cook vegetables with tamarind water and spice powder.", "Combine rice-dal with vegetable mixture.", "Add jaggery, salt, adjust consistency.", "Temper with ghee, cashews, mustard seeds.", "Serve hot with boondi raita."], time: "45 min", servings: "4", region: "Karnataka", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80", createdAt: "2026-03-06T11:00:00Z" },
  { id: "ka3", title: "Mysore Pak", description: "Rich and melt-in-mouth sweet made with besan and ghee.", ingredients: ["1 cup besan", "1 cup sugar", "1 cup ghee", "2 tbsp oil", "Cardamom"], steps: ["Make sugar syrup to one-string consistency.", "Slowly add roasted besan to syrup while stirring.", "Keep adding melted ghee in batches.", "Stir continuously until mixture leaves the pan.", "Pour into greased plate, cut when warm.", "Let it set completely before serving."], time: "30 min", servings: "12 pieces", region: "Karnataka", image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80", createdAt: "2026-03-06T12:00:00Z" },
  { id: "ka4", title: "Ragi Mudde", description: "Traditional finger millet ball served with spicy sambar.", ingredients: ["1 cup ragi flour", "2 cups water", "Salt", "Toor dal", "Mixed vegetables", "Sambar powder", "Tamarind"], steps: ["Boil water, add ragi flour slowly while stirring.", "Cook on low heat, stirring continuously to avoid lumps.", "Once thick and glossy, remove from heat.", "Wet hands and shape into smooth balls.", "Prepare sambar with dal, vegetables, tamarind.", "Serve ragi mudde with hot sambar."], time: "25 min", servings: "4", region: "Karnataka", image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&q=80", createdAt: "2026-03-06T13:00:00Z" },
  { id: "ka5", title: "Neer Dosa", description: "Thin, lacy rice crepes from coastal Karnataka.", ingredients: ["2 cups rice", "1 cup grated coconut", "Salt", "Water", "Coconut oil"], steps: ["Soak rice for 4 hours.", "Grind rice and coconut with water to thin batter.", "Heat a non-stick pan, pour batter and swirl.", "Cover and cook 1-2 minutes (no flipping needed).", "Gently fold and remove.", "Serve with chicken curry or coconut chutney."], time: "20 min", servings: "4", region: "Karnataka", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&q=80", createdAt: "2026-03-06T14:00:00Z" },

  // ─── HYDERABAD (5) ───
  { id: "h1", title: "Hyderabadi Biryani", description: "Aromatic layered rice and meat dish, Hyderabad's crown jewel.", ingredients: ["2 cups basmati rice", "500g mutton", "1 cup yogurt", "2 onions, fried", "Saffron", "Mint", "Biryani masala", "Ghee"], steps: ["Marinate mutton with yogurt, spices for 2 hours.", "Parboil rice with whole spices.", "Layer mutton and rice in heavy pot.", "Top with fried onions, saffron milk, mint.", "Seal with dough, cook on dum 45 min.", "Gently mix and serve with raita."], time: "90 min", servings: "6", region: "Hyderabad", image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80", createdAt: "2026-03-07T10:00:00Z" },
  { id: "h2", title: "Haleem", description: "Slow-cooked meat and wheat porridge, rich and hearty.", ingredients: ["500g mutton", "1 cup broken wheat", "1/2 cup chana dal", "Ginger-garlic paste", "Garam masala", "Ghee", "Fried onions", "Lemon"], steps: ["Soak wheat and dal 4 hours.", "Pressure cook mutton with spices until very tender.", "Cook wheat and dal separately until mushy.", "Combine and mash together, cook on low 30 min.", "Stir continuously for smooth texture.", "Garnish with fried onions, ghee, lemon, and mint."], time: "120 min", servings: "6", region: "Hyderabad", image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80", createdAt: "2026-03-07T11:00:00Z" },
  { id: "h3", title: "Mirchi Ka Salan", description: "Tangy peanut-sesame gravy with fried green chilies.", ingredients: ["8 large green chilies", "1/2 cup peanuts", "2 tbsp sesame seeds", "Tamarind", "Coconut", "Mustard seeds", "Curry leaves", "Oil"], steps: ["Slit and fry green chilies, set aside.", "Roast and grind peanuts, sesame, coconut.", "Sauté onions, add ground paste.", "Add tamarind water, bring to boil.", "Add fried chilies, simmer 10 min.", "Serve as biryani accompaniment."], time: "30 min", servings: "4", region: "Hyderabad", image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&q=80", createdAt: "2026-03-07T12:00:00Z" },
  { id: "h4", title: "Double Ka Meetha", description: "Hyderabadi bread pudding soaked in saffron-cardamom milk.", ingredients: ["8 bread slices", "2 cups milk", "1/2 cup sugar", "Saffron", "Cardamom", "Almonds", "Pistachios", "Ghee"], steps: ["Cut bread into triangles, fry in ghee until golden.", "Boil milk with sugar, saffron, cardamom.", "Reduce milk to half.", "Arrange fried bread in dish, pour milk over.", "Let it soak 30 min.", "Garnish with nuts, serve warm."], time: "40 min", servings: "4", region: "Hyderabad", image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80", createdAt: "2026-03-07T13:00:00Z" },
  { id: "h5", title: "Keema Samosa", description: "Crispy pastry filled with spiced minced meat.", ingredients: ["250g mutton keema", "2 cups flour", "1 onion", "Ginger-garlic paste", "Garam masala", "Green chilies", "Coriander", "Oil for frying"], steps: ["Cook keema with onions, spices until dry.", "Add coriander, green chilies, cool completely.", "Make dough with flour, salt, oil. Rest 30 min.", "Roll, cut into semi-circles, form cones.", "Fill with keema, seal edges.", "Deep fry until golden and crispy."], time: "50 min", servings: "12 pieces", region: "Hyderabad", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&q=80", createdAt: "2026-03-07T14:00:00Z" },

  // ─── RAJASTHAN (5) ───
  { id: "r1", title: "Dal Baati Churma", description: "Rajasthan's signature trio: baked wheat balls, five-lentil dal, and sweet churma.", ingredients: ["2 cups wheat flour", "Ghee", "Mixed dals (5 types)", "Onion", "Tomato", "Jaggery", "Cardamom", "Baking soda"], steps: ["Make firm dough with flour, ghee, salt. Shape into balls.", "Bake baati at 180°C for 30 min or cook in sand.", "Cook five-lentil dal with onion-tomato masala.", "Crush baked baati, mix with ghee and jaggery for churma.", "Dip baati in ghee before serving.", "Serve trio together."], time: "60 min", servings: "4", region: "Rajasthan", image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&q=80", createdAt: "2026-03-08T10:00:00Z" },
  { id: "r2", title: "Laal Maas", description: "Fiery red meat curry from the royal kitchens of Rajasthan.", ingredients: ["500g mutton", "10-15 dried red chilies", "1 cup yogurt", "2 onions", "Garlic", "Mustard oil", "Cardamom", "Cloves"], steps: ["Soak red chilies, grind to paste.", "Marinate mutton with yogurt and chili paste.", "Heat mustard oil, add whole spices.", "Brown onions, add marinated mutton.", "Cook on low heat 45 min until tender.", "Garnish with coriander, serve with bajra roti."], time: "60 min", servings: "4", region: "Rajasthan", image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80", createdAt: "2026-03-08T11:00:00Z" },
  { id: "r3", title: "Gatte Ki Sabzi", description: "Besan dumplings in spiced yogurt curry.", ingredients: ["1 cup besan", "1 cup yogurt", "Ajwain", "Red chili", "Turmeric", "Cumin", "Coriander powder", "Oil"], steps: ["Mix besan with spices and water to form dough.", "Roll into cylinders, boil in water 15 min.", "Slice into pieces.", "Make yogurt gravy with onion, tomato, spices.", "Add gatte pieces to gravy.", "Simmer 10 min. Serve with roti."], time: "35 min", servings: "4", region: "Rajasthan", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80", createdAt: "2026-03-08T12:00:00Z" },
  { id: "r4", title: "Ker Sangri", description: "Desert beans and berries cooked in traditional Rajasthani style.", ingredients: ["1 cup dried ker", "1 cup dried sangri", "2 tbsp oil", "Red chili", "Turmeric", "Amchur", "Cumin seeds", "Salt"], steps: ["Soak ker and sangri overnight, boil until tender.", "Heat oil, add cumin seeds.", "Add boiled ker sangri with spices.", "Cook on low heat 15 min.", "Add amchur for tanginess.", "Serve with bajra roti and buttermilk."], time: "30 min", servings: "4", region: "Rajasthan", image: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=600&q=80", createdAt: "2026-03-08T13:00:00Z" },
  { id: "r5", title: "Ghevar", description: "Disc-shaped sweet soaked in sugar syrup, a Rajasthani festive treat.", ingredients: ["1 cup flour", "1/2 cup ghee", "Ice cold water", "Sugar syrup", "Milk", "Saffron", "Pistachios"], steps: ["Mix flour with melted ghee and ice water to thin batter.", "Heat oil in ghevar mold.", "Pour batter in center, let it set in circular shape.", "Fry until golden and crisp.", "Soak in sugar syrup briefly.", "Top with rabdi and pistachios."], time: "45 min", servings: "6", region: "Rajasthan", image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80", createdAt: "2026-03-08T14:00:00Z" },

  // ─── BENGAL (5) ───
  { id: "b1", title: "Macher Jhol", description: "Traditional Bengali fish curry with potatoes in light mustard-turmeric gravy.", ingredients: ["500g rohu fish", "2 potatoes", "1 tsp turmeric", "1 tsp mustard paste", "4 green chilies", "Mustard oil", "Nigella seeds", "Salt"], steps: ["Marinate fish with turmeric and salt, lightly fry.", "Fry potato pieces until golden.", "Heat mustard oil, add nigella seeds.", "Add potatoes, turmeric, salt, water. Cook 10 min.", "Add mustard paste and green chilies.", "Gently add fish, simmer 10 min. Serve with rice."], time: "30 min", servings: "4", region: "Bengal", image: "https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80", createdAt: "2026-03-09T10:00:00Z" },
  { id: "b2", title: "Mishti Doi", description: "Sweetened yogurt dessert, caramelized and set to perfection.", ingredients: ["1 liter full cream milk", "1/2 cup sugar (for caramel)", "2 tbsp yogurt (starter)", "Cardamom"], steps: ["Boil milk and reduce to 3/4.", "Caramelize sugar until deep golden.", "Slowly add hot milk to caramel, stir well.", "Cool to lukewarm, add yogurt starter.", "Pour into earthen pots.", "Set in warm place 8 hours. Refrigerate before serving."], time: "20 min + 8 hr setting", servings: "4", region: "Bengal", image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80", createdAt: "2026-03-09T11:00:00Z" },
  { id: "b3", title: "Kosha Mangsho", description: "Slow-cooked mutton in thick, rich Bengali spice gravy.", ingredients: ["500g mutton", "3 onions", "1 cup yogurt", "Ginger-garlic paste", "Whole garam masala", "Bay leaf", "Mustard oil", "Sugar"], steps: ["Marinate mutton with yogurt and spices 1 hour.", "Heat mustard oil, add whole spices and bay leaf.", "Brown onions deeply, add ginger-garlic paste.", "Add marinated mutton, sear on high heat.", "Cover and cook on very low heat 60-90 min.", "Cook until oil separates and gravy coats mutton."], time: "90 min", servings: "4", region: "Bengal", image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80", createdAt: "2026-03-09T12:00:00Z" },
  { id: "b4", title: "Sandesh", description: "Delicate Bengali sweet made from fresh paneer and sugar.", ingredients: ["1 liter milk", "2 tbsp lemon juice", "1/4 cup sugar", "Cardamom", "Saffron", "Pistachios"], steps: ["Boil milk, add lemon juice to curdle.", "Strain through muslin, wash under cold water.", "Knead chenna until smooth (10 min).", "Cook with sugar on low heat until mixture leaves pan.", "Add cardamom and saffron.", "Press into molds, garnish with pistachios. Refrigerate."], time: "30 min", servings: "8 pieces", region: "Bengal", image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=600&q=80", createdAt: "2026-03-09T13:00:00Z" },
  { id: "b5", title: "Luchi with Aloo Dum", description: "Deep-fried puffed bread with spiced potato curry.", ingredients: ["2 cups maida", "Ghee", "4 potatoes", "2 tomatoes", "Ginger paste", "Cumin", "Turmeric", "Red chili", "Bay leaf"], steps: ["Make soft dough with maida, ghee, salt. Rest 30 min.", "Boil and cube potatoes.", "Sauté cumin, bay leaf, add tomatoes and spices.", "Add potatoes, cook in thick gravy.", "Roll small luchi, deep fry until puffed.", "Serve hot luchi with aloo dum."], time: "40 min", servings: "4", region: "Bengal", image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=600&q=80", createdAt: "2026-03-09T14:00:00Z" },

  // ─── GOA (5) ───
  { id: "go1", title: "Goan Fish Curry", description: "Coconut-based fish curry with kokum and Goan spices.", ingredients: ["500g pomfret/kingfish", "1 cup grated coconut", "4 dried red chilies", "Kokum", "Tamarind", "Turmeric", "Coriander seeds", "Onion"], steps: ["Grind coconut, red chilies, coriander, turmeric to paste.", "Sauté onion, add ground paste.", "Add water, kokum, tamarind, bring to boil.", "Add fish pieces gently.", "Cook on low 10-12 min.", "Serve hot with steamed rice."], time: "30 min", servings: "4", region: "Goa", image: "https://images.unsplash.com/photo-1631292784640-2b24be784d5d?w=600&q=80", createdAt: "2026-03-10T10:00:00Z" },
  { id: "go2", title: "Pork Vindaloo", description: "Hot and sour pork curry with vinegar, a Portuguese-Goan classic.", ingredients: ["500g pork", "8 dried red chilies", "1/4 cup vinegar", "8 garlic cloves", "1 inch ginger", "Cumin", "Cloves", "Cinnamon", "Jaggery"], steps: ["Grind chilies, garlic, ginger, spices with vinegar.", "Marinate pork with paste for 4 hours.", "Sauté onions until brown.", "Add marinated pork, cook on high 5 min.", "Add water, cook on low 45 min until tender.", "Add jaggery for balance. Serve with rice or pao."], time: "60 min", servings: "4", region: "Goa", image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80", createdAt: "2026-03-10T11:00:00Z" },
  { id: "go3", title: "Bebinca", description: "Traditional Goan layered coconut pudding dessert.", ingredients: ["1 cup coconut milk", "1 cup sugar", "10 egg yolks", "1/2 cup flour", "Nutmeg", "Cardamom", "Ghee"], steps: ["Mix coconut milk, sugar, egg yolks, flour.", "Add nutmeg and cardamom.", "Grease baking dish, pour one thin layer.", "Bake at 180°C until set.", "Add another layer, bake again. Repeat 7-10 times.", "Cool completely, slice and serve."], time: "120 min", servings: "8", region: "Goa", image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80", createdAt: "2026-03-10T12:00:00Z" },
  { id: "go4", title: "Xacuti", description: "Complex Goan curry with roasted spices and poppy seeds.", ingredients: ["500g chicken", "1 cup grated coconut", "Poppy seeds", "Star anise", "Cloves", "Cinnamon", "Nutmeg", "Red chilies", "Tamarind"], steps: ["Dry roast coconut, poppy seeds, and all spices.", "Grind roasted ingredients to fine paste.", "Sauté onions, add ground paste.", "Add chicken, cook on medium heat.", "Add tamarind water, simmer until chicken is tender.", "Thick gravy should coat the chicken."], time: "45 min", servings: "4", region: "Goa", image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80", createdAt: "2026-03-10T13:00:00Z" },
  { id: "go5", title: "Sorak Curry", description: "Simple Goan coconut curry served over rice, a daily staple.", ingredients: ["1 cup grated coconut", "2 dried red chilies", "1 tsp coriander seeds", "Tamarind", "Turmeric", "Onion", "Green chilies", "Kokum"], steps: ["Grind coconut with red chilies, coriander, turmeric.", "Dissolve paste in water.", "Sauté sliced onion, add coconut mixture.", "Add kokum and green chilies.", "Simmer 15 min until flavors meld.", "Serve over steamed rice."], time: "20 min", servings: "4", region: "Goa", image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=600&q=80", createdAt: "2026-03-10T14:00:00Z" },
];

// Local storage helpers
const STORAGE_KEY = "recipeai_recipes";

export function getLocalRecipes(): RecipeData[] {
  try {
    const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]");
    return stored.length > 0 ? stored : DEMO_RECIPES;
  } catch {
    return DEMO_RECIPES;
  }
}

export function saveLocalRecipe(recipe: Partial<RecipeData>): RecipeData {
  const recipes = getLocalRecipes();
  const newRecipe: RecipeData = {
    id: crypto.randomUUID(),
    title: recipe.title || "Untitled Recipe",
    description: recipe.description || "",
    ingredients: recipe.ingredients || [],
    steps: recipe.steps || [],
    time: recipe.time || "",
    servings: recipe.servings || "",
    region: recipe.region || "",
    image: recipe.image,
    videoUrl: recipe.videoUrl,
    createdAt: new Date().toISOString(),
  };
  recipes.unshift(newRecipe);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(recipes));
  return newRecipe;
}

export function deleteLocalRecipe(id: string): void {
  const recipes = getLocalRecipes().filter((r) => r.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(recipes));
}

// API calls (fallback to local)
export async function saveRecipe(recipe: RecipeData, imageFile?: File): Promise<RecipeData> {
  try {
    const formData = new FormData();
    formData.append("recipe", JSON.stringify(recipe));
    if (imageFile) formData.append("image", imageFile);
    const res = await fetch(`${API_BASE_URL}/recipes/save`, { method: "POST", body: formData });
    if (!res.ok) throw new Error();
    return res.json();
  } catch {
    return saveLocalRecipe(recipe);
  }
}

export async function deleteRecipe(id: string): Promise<void> {
  try {
    const res = await fetch(`${API_BASE_URL}/recipes/${id}`, { method: "DELETE" });
    if (!res.ok) throw new Error();
  } catch {
    deleteLocalRecipe(id);
  }
}
