import jsPDF from "jspdf";
import type { RecipeData } from "@/lib/api";

export function exportSingleRecipePdf(recipe: RecipeData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  const checkPage = (needed: number) => {
    if (y + needed > 270) { doc.addPage(); y = 25; }
  };

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(234, 120, 30);
  doc.text(recipe.title, margin, y);
  y += 10;

  // Meta
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  const meta = [recipe.region, recipe.time, recipe.servings].filter(Boolean).join("  •  ");
  doc.text(meta, margin, y);
  y += 8;

  // Description
  if (recipe.description) {
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    const descLines = doc.splitTextToSize(recipe.description, contentWidth);
    checkPage(descLines.length * 6);
    doc.text(descLines, margin, y);
    y += descLines.length * 6 + 6;
  }

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Ingredients
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("Ingredients", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  recipe.ingredients.forEach((ing) => {
    checkPage(7);
    doc.text(`•  ${ing}`, margin + 4, y);
    y += 7;
  });
  y += 6;

  // Steps
  checkPage(15);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 30, 30);
  doc.text("Step-by-Step Method", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  recipe.steps.forEach((step, i) => {
    const stepText = `${i + 1}. ${step}`;
    const lines = doc.splitTextToSize(stepText, contentWidth - 4);
    checkPage(lines.length * 6 + 4);
    doc.text(lines, margin + 4, y);
    y += lines.length * 6 + 4;
  });

  // Footer
  y += 10;
  checkPage(10);
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by Native Indian Recipe AI", margin, y);

  doc.save(`${recipe.title.replace(/\s+/g, "_")}.pdf`);
}

export function exportRecipeBookPdf(recipes: RecipeData[], options?: { addCover?: boolean }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Cover page
  if (options?.addCover) {
    doc.setFontSize(32);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(234, 120, 30);
    doc.text("Native Indian", pageWidth / 2, 80, { align: "center" });
    doc.text("Recipe Book", pageWidth / 2, 95, { align: "center" });

    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`${recipes.length} Traditional Recipes`, pageWidth / 2, 115, { align: "center" });
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, 125, { align: "center" });

    // Table of contents
    doc.addPage();
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Table of Contents", margin, 30);

    let tocY = 45;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    recipes.forEach((r, i) => {
      if (tocY > 270) { doc.addPage(); tocY = 30; }
      doc.setTextColor(60, 60, 60);
      doc.text(`${i + 1}. ${r.title}`, margin, tocY);
      doc.setTextColor(150, 150, 150);
      doc.text(r.region || "", pageWidth - margin, tocY, { align: "right" });
      tocY += 8;
    });
  }

  // Recipe pages
  recipes.forEach((recipe, idx) => {
    if (idx > 0 || options?.addCover) doc.addPage();
    let y = 25;

    const checkPage = (needed: number) => {
      if (y + needed > 270) { doc.addPage(); y = 25; }
    };

    // Title
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(234, 120, 30);
    doc.text(recipe.title, margin, y);
    y += 9;

    // Meta
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    const meta = [recipe.region, recipe.time, recipe.servings].filter(Boolean).join("  •  ");
    doc.text(meta, margin, y);
    y += 8;

    if (recipe.description) {
      doc.setFontSize(10);
      doc.setTextColor(80, 80, 80);
      const descLines = doc.splitTextToSize(recipe.description, contentWidth);
      checkPage(descLines.length * 5);
      doc.text(descLines, margin, y);
      y += descLines.length * 5 + 5;
    }

    doc.setDrawColor(220, 220, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Ingredients
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Ingredients", margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    recipe.ingredients.forEach((ing) => {
      checkPage(6);
      doc.text(`•  ${ing}`, margin + 3, y);
      y += 6;
    });
    y += 5;

    // Steps
    checkPage(12);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Method", margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    recipe.steps.forEach((step, i) => {
      const text = `${i + 1}. ${step}`;
      const lines = doc.splitTextToSize(text, contentWidth - 3);
      checkPage(lines.length * 5 + 3);
      doc.text(lines, margin + 3, y);
      y += lines.length * 5 + 3;
    });

    // Page number
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(`${idx + 1} / ${recipes.length}`, pageWidth / 2, 285, { align: "center" });
  });

  doc.save("Native_Indian_Recipe_Book.pdf");
}
